### ISSUE TITLE
Wrong palette for Pocket Camera

### ISSUE THREAD

**Issue by 1ukeman** [HerrZatacke/gb-palettes#1]
Game Boy Color's Up palette and Pocket Camera's Game Boy Color palette are two different distinct palettes, but you treat them as if they were identical.

Exact color values for Pocket Camera's palette:
#FFFFFF | #FFCE00 | #9C6300 | #000000

Up palette:
![Pocket Camera (Japan) (Rev 1) (SGB Enhanced)-240419-082631](https://github.com/HerrZatacke/gb-palettes/assets/73172684/87792d7d-7700-44a5-8571-be4e1984adb5)
Pocket Camera's default palette:
![Pocket Camera (Japan) (Rev 1) (SGB Enhanced)-240419-082611](https://github.com/HerrZatacke/gb-palettes/assets/73172684/ec4a7aa7-945d-445e-97fb-81d77ae5dbb9)

Up palette:
![Up](https://github.com/HerrZatacke/gb-palettes/assets/73172684/8bfa3239-437c-4317-a76f-2bdeb7d55a5e)
Pocket Camera's default palette:
![PocketCamera](https://github.com/HerrZatacke/gb-palettes/assets/73172684/33071e3a-d7aa-4693-8ed1-e082d5af279a)
While they might look similar on actual hardware, they're still two different palettes.

**Comment by HerrZatacke** [comment]
Thanks for your contribution. I noticed the difference a while ago, but then totally forgot about it.
In case you expect it to appear in the [web-app](https://github.com/HerrZatacke/gb-printer-web): It will do so automatically with the next release.
